"""
    Please do not edit this file if you do not know what you are doing, it might break everything.
"""

import discord
from discord.utils import utcnow

def normalize_kwargs(**kwargs):
    return {k.lower(): v for k, v in kwargs.items()}

def create_embed(title, description, color, footer="WinUtil"):
    embed = discord.Embed(
        title=title,
        description=description
    )
    embed.set_footer(text=footer)
    embed.timestamp = utcnow()
    try:
        embed.color = discord.Colour.from_str(color)
    except ValueError:
        embed.color = discord.Colour.default()
    return embed

DEFAULT_COLOR = "#1983bd"
ERROR_COLOR = "#5c1212"
SUCCESS_COLOR = "#184128"

def DefaultEmbed(**kwargs):
    kwargs = normalize_kwargs(**kwargs)
    title = kwargs.get('title', 'N/A')
    description = kwargs.get('description', 'N/A')
    color = kwargs.get('color', DEFAULT_COLOR)
    title = f"<:ctt:1261993408306745405> {title}"
    return create_embed(title, description, color)

def ProtectedEmbed(**kwargs):
    kwargs = normalize_kwargs(**kwargs)
    title = kwargs.get('title', 'N/A')
    description = kwargs.get('description', 'N/A')
    color = kwargs.get('color', DEFAULT_COLOR)
    title = f"<:security:1261995399611420673> {title}"
    return create_embed(title, description, color)

def ErrorEmbed(**kwargs):
    kwargs = normalize_kwargs(**kwargs)
    title = kwargs.get('title', 'N/A')
    description = kwargs.get('description', 'N/A')
    title = f"<:Red_X:1264637740662652939> {title}"
    return create_embed(title, description, ERROR_COLOR)

def SuccessEmbed(**kwargs):
    kwargs = normalize_kwargs(**kwargs)
    title = kwargs.get('title', 'N/A')
    description = kwargs.get('description', 'N/A')
    title = f"<:Green_Checkmark:1264637765677482185> {title}"
    return create_embed(title, description, SUCCESS_COLOR)
